# Generated by Django 4.2.28 on 2026-03-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skill",
            options={"ordering": ["name"], "verbose_name_plural": "Skills"},
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="ai_suggestions",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="ats_analysis",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="ats_recommendations",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="career_stage",
            field=models.CharField(
                choices=[
                    ("entry", "Entry-level"),
                    ("junior", "Junior"),
                    ("mid", "Mid-level"),
                    ("senior", "Senior"),
                    ("executive", "Executive"),
                ],
                default="mid",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="industry_match",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="pattern_issues",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="resume_quality_summary",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="resumeanalysis",
            name="strengths",
            field=models.JSONField(default=list),
        ),
    ]
